version: '3'
services:
  mongo:
    image: 'mongo:3.6'
    ports:
      - '27017:27017'
    volumes:
      - './hidden_data/mongo:/data/db'
    

  app:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "80:80"

    environment:
      - SECRETKEY=your_key
